# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtChat.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1528, 1103)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.ChatTable = QtWidgets.QFrame(self.centralwidget)
        self.ChatTable.setStyleSheet("QFrame{\n"
"    background:rgb(41, 41, 41)\n"
"}")
        self.ChatTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ChatTable.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ChatTable.setObjectName("ChatTable")
        self.send_button = QtWidgets.QPushButton(self.ChatTable)
        self.send_button.setGeometry(QtCore.QRect(1230, 910, 221, 61))
        self.send_button.setStyleSheet("QPushButton{\n"
"    background: rgb(100, 200, 100);\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                stop:0 rgb(100, 200, 100), \n"
"                                stop:1 rgb(120, 220, 120)  \n"
"                               );\n"
"}")
        self.send_button.setObjectName("send_button")
        self.message_input = QtWidgets.QTextEdit(self.ChatTable)
        self.message_input.setGeometry(QtCore.QRect(510, 910, 711, 61))
        self.message_input.setStyleSheet("QTextEdit{\n"
"    background: rgb(203, 203, 203);\n"
"    border-radius: 12px;\n"
"\n"
"}")
        self.message_input.setObjectName("message_input")
        self.message_recv = QtWidgets.QListWidget(self.ChatTable)
        self.message_recv.setGeometry(QtCore.QRect(510, 10, 951, 881))
        self.message_recv.setStyleSheet("QListWidget {\n"
"    background-color: #e0e0e0; \n"
"}\n"
"\n"
"QListWidget::item {\n"
"    background-color: #ffffff;\n"
"    border-radius: 10px;\n"
"    padding: 10px; /* 设置内边距 */\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #c0c0c0;\n"
"}\n"
"")
        self.message_recv.setObjectName("message_recv")
        self.layoutWidget = QtWidgets.QWidget(self.ChatTable)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.username_input = QtWidgets.QTextEdit(self.ChatTable)
        self.username_input.setGeometry(QtCore.QRect(20, 720, 451, 61))
        self.username_input.setStyleSheet("QTextEdit{\n"
"    background: rgb(203, 203, 203);\n"
"    border-radius: 12px;\n"
"\n"
"}")
        self.username_input.setObjectName("username_input")
        self.label_2 = QtWidgets.QLabel(self.ChatTable)
        self.label_2.setGeometry(QtCore.QRect(20, 540, 451, 161))
        self.label_2.setStyleSheet("QLabel{\n"
"    background:rgb(145, 145, 145);\n"
"    border-radius: 20px;\n"
"}")
        self.label_2.setObjectName("label_2")

        self.password_input = QtWidgets.QTextEdit(self.ChatTable)
        self.password_input.setGeometry(QtCore.QRect(20, 810, 451, 61))
        self.password_input.setStyleSheet("QTextEdit{\n"
"    background: rgb(203, 203, 203);\n"
"    border-radius: 12px;\n"
"\n"
"}")
        self.password_input.setObjectName("password_input")
        self.login_button = QtWidgets.QPushButton(self.ChatTable)
        self.login_button.setGeometry(QtCore.QRect(10, 910, 221, 61))
        self.login_button.setStyleSheet("QPushButton{\n"
"    background: rgb(100, 200, 100);\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                stop:0 rgb(100, 200, 100), \n"
"                                stop:1 rgb(120, 220, 120)  \n"
"                               );\n"
"}")
        self.login_button.setObjectName("login_button")
        self.signup_button = QtWidgets.QPushButton(self.ChatTable)
        self.signup_button.setGeometry(QtCore.QRect(250, 910, 221, 61))
        self.signup_button.setStyleSheet("QPushButton{\n"
"    background: rgb(100, 200, 100);\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    }\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                stop:0 rgb(100, 200, 100), \n"
"                                stop:1 rgb(120, 220, 120)  \n"
"                               );\n"
"}")
        self.signup_button.setObjectName("signup_button")
        self.listWidget_2 = QtWidgets.QListWidget(self.ChatTable)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 10, 489, 521))
        self.listWidget_2.setStyleSheet("QListWidget{\n"
"background:rgb(188, 188, 188);\n"
"}")
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout.addWidget(self.ChatTable, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1528, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.send_button.setText(_translate("MainWindow", "Send"))
        self.username_input.setPlaceholderText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.password_input.setPlaceholderText(_translate("MainWindow", "Passowrd"))
        self.login_button.setText(_translate("MainWindow", "LogIn"))
        self.signup_button.setText(_translate("MainWindow", "SignUP"))
